const studentList = [
  {
    student_id: 1,
    student_name: "Kristina",
    student_lastName: "Zylfa",
    grades: {
      math: 90,
      literature: 85,
      physics: 78,
      chemistry: 92,
      geography: 88,
      history: 95,
    },
    student_class: 10,
  },
  {
    student_id: 2,
    student_name: "Klea",
    student_lastName: "Basha",
    grades: {
      math: 88,
      literature: 92,
      physics: 85,
      chemistry: 90,
      geography: 78,
      history: 94,
    },
    student_class: 11,
  },
  {
    student_id: 3,
    student_name: "Edi",
    student_lastName: "Jonuzaj",
    grades: {
      math: 95,
      literature: 87,
      physics: 92,
      chemistry: 89,
      geography: 90,
      history: 91,
    },
    student_class: 10,
  },
  {
    student_id: 4,
    student_name: "Ajla",
    student_lastName: "Shakohoxha",
    grades: {
      math: 80,
      literature: 75,
      physics: 82,
      chemistry: 78,
      geography: 85,
      history: 79,
    },
    student_class: 11,
  },
  {
    student_id: 5,
    student_name: "Petrit",
    student_lastName: "Hoxha",
    grades: {
      math: 64,
      literature: 75,
      physics: 72,
      chemistry: 84,
      geography: 94,
      history: 98,
    },
    student_class: 12,
  },
  {
    student_id: 6,
    student_name: "Kristi",
    student_lastName: "Veliu",
    grades: {
      math: 80,
      literature: 75,
      physics: 82,
      chemistry: 78,
      geography: 85,
      history: 79,
    },
    student_class: 12,
  },
  {
    student_id: 7,
    student_name: "Ami",
    student_lastName: "Ndoj",
    grades: {
      math: 50,
      literature: 45,
      physics: 32,
      chemistry: 78,
      geography: 85,
      history: 79,
    },
    student_class: 11,
  },
  {
    student_id: 8,
    student_name: "Ardi",
    student_lastName: "Bushi",
    grades: {
      math: 80,
      literature: 75,
      physics: 82,
      chemistry: 78,
      geography: 85,
      history: 79,
    },
    student_class: 10,
  },
  {
    student_id: 9,
    student_name: "Kristi",
    student_lastName: "Veliu",
    grades: {
      math: 50,
      literature: 55,
      physics: 52,
      chemistry: 58,
      geography: 65,
      history: 69,
    },
    student_class: 10,
  },
  {
    student_id: 10,
    student_name: "Bjorni",
    student_lastName: "Shaha",
    grades: {
      math: 64,
      literature: 25,
      physics: 42,
      chemistry: 68,
      geography: 95,
      history: 77,
    },
    student_class: 11,
  },

];

export default studentList;
